# Generated by Django 6.0.2 on 2026-02-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsuleaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='privatevaultitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timecapsule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaultaccesstoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaultpermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CapsuleMusicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_vibe', models.CharField(choices=[('chaotic', 'Chaotic'), ('wholesome', 'Wholesome'), ('dramatic', 'Dramatic'), ('late_night', 'Late Night Core'), ('exam_survival', 'Exam Survival'), ('heartbreak', 'Heartbreak Era'), ('party', 'Party Anthem'), ('chill', 'Chill Vibes')], default='chill', max_length=50)),
                ('avg_valence', models.FloatField(default=0.5)),
                ('avg_energy', models.FloatField(default=0.5)),
                ('avg_danceability', models.FloatField(default=0.5)),
                ('shared_anthem_track_id', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_playlist_id', models.CharField(blank=True, max_length=100, null=True)),
                ('compatibility_heatmap', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_analysis', to='vault.timecapsule')),
            ],
        ),
    ]
