# Generated by Django 6.0.2 on 2026-02-14 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('post_newsroom', 'New Post in Newsroom'), ('post_group', 'New Post in Group'), ('post_community', 'New Post in Community'), ('group_created', 'New Group Created'), ('community_created', 'New Community Created'), ('capsule_unlocked', 'Time Capsule Unlocked'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('community_id', models.IntegerField(blank=True, null=True)),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
