# Generated by Django 6.0.2 on 2026-02-14 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cupidconsent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cupidconsent',
            name='nomination',
        ),
        migrations.RemoveField(
            model_name='cupidconsent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cupidmatch',
            name='group',
        ),
        migrations.RemoveField(
            model_name='cupidmatch',
            name='user_a',
        ),
        migrations.RemoveField(
            model_name='cupidmatch',
            name='user_b',
        ),
        migrations.RemoveField(
            model_name='cupidnomination',
            name='group',
        ),
        migrations.RemoveField(
            model_name='cupidnomination',
            name='nominated_by',
        ),
        migrations.RemoveField(
            model_name='cupidnomination',
            name='user_a',
        ),
        migrations.RemoveField(
            model_name='cupidnomination',
            name='user_b',
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='relationshipedge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='relationshipedge',
            name='group',
        ),
        migrations.RemoveField(
            model_name='relationshipedge',
            name='source_user',
        ),
        migrations.RemoveField(
            model_name='relationshipedge',
            name='target_user',
        ),
        migrations.AlterUniqueTogether(
            name='wallrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wallrole',
            name='group',
        ),
        migrations.RemoveField(
            model_name='wallrole',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='groups_mess_group_i_4269f4_idx',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='allow_cupid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='allow_relationship_graph',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CupidConsent',
        ),
        migrations.DeleteModel(
            name='CupidMatch',
        ),
        migrations.DeleteModel(
            name='CupidNomination',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='RelationshipEdge',
        ),
        migrations.DeleteModel(
            name='WallRole',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_ephemeral',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='text',
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user')},
        ),
    ]
