# Generated by Django 6.0.2 on 2026-02-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('most_likely_to', 'Most Likely To'), ('skribbl', 'Skribbl'), ('cupid', 'Cupid')], max_length=50),
        ),
    ]
