# Generated by Django 6.0.2 on 2026-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_points_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
