# Generated by Django 6.0.2 on 2026-02-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_id_alter_communitycomment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(choices=[('meme', 'Meme'), ('roast', 'Roast'), ('confession', 'Confession'), ('joke', 'Joke'), ('inside_joke', 'Inside Joke'), ('casual', 'Casual'), ('news_bite', 'News Bite'), ('image', 'Image')], default='casual', max_length=20),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
