# Generated by Django 6.0.2 on 2026-02-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonRecap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_activities', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('most_active_user_id', models.IntegerField(blank=True, null=True)),
                ('most_chaotic_day', models.DateField(blank=True, null=True)),
                ('longest_streak', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'unique_together': {('group', 'start_date', 'end_date')},
            },
        ),
    ]
