# Generated by Django 6.0.2 on 2026-02-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonrecap',
            name='anthem_track',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='seasonrecap',
            name='dominant_vibe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
